baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "It's always a feature"
theme = "PaperMod"

[build]
  publishResources = true
  noChmod = true
  writeStats = true

[params]
  showDrafts = true  # Globally hides drafts